### ISSUE TITLE
Threre is no "setTextAppearance()" method in TextLayoutBuilder

### ISSUE THREAD

**Issue by kingty** [facebookincubator/TextLayoutBuilder#4]

**Comment by ahmedre** [comment]
you can use `ResourceTextLayoutHelper.setTextAppearance`

**Comment by sriramramani** [comment]
Closing this as we have a solution for this. We will try to pull the `setTextAppearance` from `ResourceTextLayoutHelper` into `TextLayoutBuilder` in the future. Thanks for reporting this.
