### ISSUE TITLE
the hide constructor method  of android.text.StaticLayout

### ISSUE THREAD

**Issue by anql** [facebookincubator/TextLayoutBuilder#5]
### android.text.StaticLayout
the constructor method  with 'int maxLines' param is a hide method.
Does StaticLayoutProxy.java can new StaticLayout object with the 'maxLines' directly?

```java
    /**
     * @hide
     */
    public StaticLayout(CharSequence source, int bufstart, int bufend,
                        TextPaint paint, int outerwidth,
                        Alignment align, TextDirectionHeuristic textDir,
                        float spacingmult, float spacingadd,
                        boolean includepad,
                        TextUtils.TruncateAt ellipsize, int ellipsizedWidth, int maxLines) {
```

**Comment by ahmedre** [comment]
the `@hide` constructor has been there across all API versions so far. `textlayoutbuilder` has a "compile time only" dependency on the proxy), which is available on the device at runtime.

**Comment by sriramramani** [comment]
As @ahmedre mentioned, the hidden constructor is accessed through the `StaticLayoutProxy` class. This class is available from `com.facebook.fbui.textlayoutbuilder:staticlayout-proxy:1.0` dependency. Closing this issue as this works fine as expected. Thanks for reporting.
