### ISSUE TITLE
GlyphWarmerImpl's Picture is not drawn on View?

### ISSUE THREAD

**Issue by Shuijwan** [facebookincubator/TextLayoutBuilder#7]
In GlyphWarmerImpl, the textlayout is drawn to a Picture on separate thread, however it seems this Picture is not used, and not drawn on the real view?

**Comment by ahmedre** [comment]
this is intentional to warm the font cache - from the documentation:

> On 4.0+ devices, TextLayoutBuilder can warm up the FreeType font cache. By drawing these glyphs on a background thread onto a Picture, TextLayoutBuilder warms these glyphs and can help reduce their render time.

**Comment by ahmedre** [comment]
also, if you want to disable this behavior, you can leave out the `setGlyphWarmer` call on your builder.
